# Site settings
title: Jan Keim
twitter_username: _Gramy_
name: Jan Keim

# Build settings
markdown: kramdown

#User specific content
#Links that will appear in the navbar
primarylinks:
 - title: Mail
   url: mailto:mail@janke.im
 - title: GitHub
   url: https://github.com/Gram21
 - title: Twitter
   url: https://twitter.com/_Gramy_
 - title: Publications
   url: https://are.ipd.kit.edu/people/jan-keim/publications/
 - title: ORCID
   url: https://orcid.org/0000-0002-8899-7081
 - title: Google Scholar
   url: https://scholar.google.com/citations?user=fC9DrioAAAAJ



#Any buzzword skills you want to include
skills:
 - Software Architecture
 - Software Architecture Documentation
 - Natural Language Processing
 - Machine learning
 - Ontologies
 - Teaching
 - Java
 - EMF/Ecore
 - Python
 - Rust

#Work experience is required
roles:
 - title: Researcher
   start: 2018
   end: Ongoing
   employer: Karlsruhe Institute of Technology (KIT)
   description: Researcher in the area of Software Engineering, more specifically Software Architecture Documentation Consistency. Also, teaching is involved.
 - title: Student worker
   start: 2013
   end: 2018
   employer: Karlsruhe Institute of Technology (KIT)
   description: Tutor for the lectures Software Engineering I (SWT I) and Programming. Additionally, assisting in research.


#Education is required
education:
 - level: Master of Science (M.Sc.)
   date: 2018
   subject: Computer Science
   school: Karlsruhe Institute of Technology (KIT)
 - level: Bachelor of Science (B.Sc.)
   date: 2015
   subject: Computer Science
   school: Karlsruhe Institute of Technology (KIT)

#This section is optional (as is the image link below)
# coursera:
#    profileurl:
#    courses:
#     - title:
#       link:
#       optionalimage:
#       date:


#This section is optional - embeds slideshows from speakerdeck
# to get the speakerdeck ID copy the embed code and look for the data-it attribute
# speakerdeck:
#    profileurl:
#    talks:
#     - title:
#       speakerdeckId:
#       conference:


#List of interesting Github repo/projects to include - optional
github:
 - Gram21/BERT4DAT
 - tobhey/NoRBERT
 - Gram21/GPUSorting
 - Gram21/pasters
 - kit-sdq/Ecore2OWL
 - InFormALin/Ontology-Connector

#Stackoverflow flair is optional
# stackoverflow:
#    profileurl:
#    flairimageurl:

intro: |
  <img src="img/gravatar.jpeg" style="float:left; border: 5px solid transparent;" width="100" height="100"/>
  I am a computer scientist (M.Sc.) from Karlsruhe, Germany. I am generally interested in programming, especially in Java, Python, and Rust.
  I am also a Researcher at KIT in the domain of Software Architecture Documentation and Natural Language Programming (NLP).
  At my job, I am also resposible for teaching students in different areas around Programming, Software Engineering, and Research. You can find more on <a href="https://are.ipd.kit.edu/people/jan-keim/">my institute page</a>.

#An additional info freetext section is optional at the bottom of the page - can be text or HTML
additionalinfo: |
  <strong>Java</strong>: I am experienced in a variety of Java API’s and frameworks. Additionally, I worked with the <strong>Eclipse</strong> RCP and Maven Tycho. <br/><br/>
  <strong>EMF/Ecore</strong>: In my research, I also worked a lot with EMF/Ecore and similar MDSD tools. <br/><br/>
  <strong>Rust</strong>: I did some Rust and have most basic knowledge. However, I would not call me an expert or really advanced developer.
